[package]
name = "scaffolding-terminal"
version = "0.1.0"
authors = ["Without Boats <woboats@gmail.com>"]
license = "AGPL-3.0+"

[dependencies]
gdk = "*"
gtk = "*"
cairo-rs = "*"

[dependencies.tty]
path = "tty"

[dependencies.pangocairo]
path = "pangocairo"

[dependencies.notty]
path = ".."

